/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_areamobile_apis_hw_pics_utils_JNITalker */

#ifndef _Included_eu_areamobile_apis_hw_pics_utils_JNITalker
#define _Included_eu_areamobile_apis_hw_pics_utils_JNITalker

/*
 * Class:     eu_areamobile_apis_hw_pics_utils_JNITalker
 * Method:    attaching
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_eu_areamobile_apis_hw_pics_utils_JNITalker_attaching (JNIEnv *, jobject);
#endif
